### PR TITLE
Build both cpu and gpu binaries

### PR DESCRIPTION
**Pull request by kkleidal**
This way, a docker image containing the GPU package will still run when on a CPU-only machine, as might be the case during testing. This is the same behavior as the pytorch package.

### CODE REVIEW

**Comment by rusty1s** [comment]
Thanks, I will try to merge since by the end of the year.

**Comment by kkleidal** [comment]
Hi @rusty1s . Just checking in on this. Let me know if there is anything I can do to help 😄

**Comment by rusty1s** [comment]
I will try to merge this soon. Sorry for the delay. Finally have time to look into it.

**Comment by rusty1s** [comment]
Looks like there is indeed no elegant way to allow this behavior without building separate binaries. What a bummer. One solution would be to separate CPU and CUDA functionality in C++ code, but this results in a lot of duplicated code, and we would need to call the correct method in Python dependent on whether we are operating on CUDA or CPU tensors.
Interestingly, `torchvision` does not allow CUDA wheels on CPU-only machines either.

Nevertheless, I pushed some experimental changes to [`torch-spline-conv`](https://github.com/rusty1s/pytrtorch_spline_conv/commit/eb9f24b51804cc68537a91b615e64aff89eb145f) to see how those affect build times in our CI. In case they are there reasonable, I will merge this in.

**Comment by rusty1s** [comment]
I already updated `torch-spline-conv` and `torch-cluster` with the proposed changes. This one is next :) Wheels for `torch-scatter` will be released soon. Thank you very much!

**Comment by kkleidal** [comment]
Thank you! 😃

**Comment by rusty1s** [comment]
Done! Please confirm that it is working as expected.

**Comment by kkleidal** [comment]
It's working as expected! Thank you! It feels good to get rid of the private fork and use the official release 😄

**Pull request merged**
