### PR TITLE
fix: add torch as build dependency

### PR DESCRIPTION
**Pull request by johanfleury**
Allows adding torch-scatter and torch in the same `requirements.txt` file.

### CODE REVIEW

**Comment by rusty1s** [comment]
This is sadly not possible, since we import torch in the same file :(

**Comment by johanfleury** [comment]
Arg, didn't see that.

How can one have a complete `requirements.txt` within their project then?

**Comment by rusty1s** [comment]
I asked myself that too. Sadly, python does not allow a sequential installation of the requirement file. There are other packages having the same problem, *e.g., `chyton` and packages that depend on it. I do not think there is a way to fix this as long as python ignores these kind of problems.

**Comment by rusty1s** [comment]
I am closing this for now. Maybe we can come up with an alternative way to fix this soon.

**Pull request closed without merging**
