### PR TITLE
Export symbols for Windows DLL and MSVC build compatibility

### PR DESCRIPTION
**Pull request by GericoVi**
Export DLL symbols for Windows and MSVC build compatibility. Related to #290

### CODE REVIEW

**Comment by rusty1s** [comment]
I missed this PR, I am really sorry. I am happy to merge it once tests pass. Let me know if you need any help in fixing those.

**Comment by GericoVi** [comment]
I've since revisited this and the linking failure seems to only occur with the `cuda_version` symbol. The others seem to export properly.

I.e. commenting out these lines:
```python
namespace scatter {
SCATTER_API int64_t cuda_version() noexcept;

namespace detail {
SCATTER_INLINE_VARIABLE int64_t _cuda_version = cuda_version();
} // namespace detail
} // namespace scatter
```

in scatter.h allows `setup.py` to run to completion and install. But I'm assuming the package won't work correctly in Python without this functionality.

Trying to investigate why this symbol doesn't export correctly. The setup seems to be the same as in the `pytorch_sparse` symbol export and also in the new rusty1s/pytorch_cluster#132.

**Comment by GericoVi** [comment]
I have a feeling that it has something to do with the fact that the main header `scatter.h` is also associated with a code file (`scatter.cpp`). While in `torch_sparse` and `torch_cluster`, their respective headers (`sparse.h` and `cluster.h`) only serve to declare functions (including the `cuda_version`) and don't have a corresponding `*.cpp` file - they're not even really included anywhere in the c source.

This is really the only thing I can see that's different between the implementations in those repos which worked and here where it isn't. Note, the other files build and link correctly (especially notably `version.cpp` has no problem linking even though it contains the `cuda_version` symbol).

The above commit brings the changes even more inline with the export symbols PRs in the other repos. But unsure how to fully fix - needs separation of `scatter.cpp` into individual files maybe? Maybe a bit out of scope for this PR, @rusty1s?

**Comment by GericoVi** [comment]
So it works now? By removing the `#include "scatter.h"` from `scatter.cpp`.

I don't have enough C++/Python extension knowledge to know why that works or if it's a bad solution. So I'll leave it up to others...

**Review by rusty1s — APPROVED** [review]

**Comment by rusty1s** [comment]
Thank you! The "fix" makes sense.

**Pull request merged**
