### PR TITLE
Use `static constexpr` for VS compilation

### PR DESCRIPTION
**Pull request by HunterTracer**
static constexpr should be used in macro in cuda/reducer.cuh, otherwise VS compilation will fail with error C2975: 'REDUCE': invalid template argument for 'Reducer', expected compile-time constant expression

### CODE REVIEW

**Review by rusty1s — APPROVED** [review]
thanks!

**Comment by rusty1s** [comment]
It looks like this breaks our current Windows build in the CI. Do you know why?

**Comment by HunterTracer** [comment]
It seems a bug in pytorch release version. There is a conflict between include/ATen/Parallel.h inline implementation of void lazy_init_num_threads and libs in pytorch release, a simple solution is to remove the inline TORCH_API void lazy_init_num_threads() implementation and only keeps TORCH_API void lazy_init_num_threads();. A similar answer can be found in https://stackoverflow.com/questions/74366357/updating-to-visual-studio-17-4-0-yields-linker-errors-related-to-tls

**Comment by HunterTracer** [comment]
Another way is to rebuild libtorch by ourselves and not use the official release version

**Comment by rusty1s** [comment]
Thanks! I did something similar here: https://github.com/pyg-team/pyg-lib/blob/master/.github/actions/setup/action.yml#L42. Can we add the patching of `Parallel.h` as part of our CI?

**Comment by HunterTracer** [comment]
I think it's ok. The only thing need to do is to replace
```
inline TORCH_API void lazy_init_num_threads() {
  thread_local bool init = false;
  if (C10_UNLIKELY(!init)) {
    at::init_num_threads();
    init = true;
  }
}
```
to
`TORCH_API void lazy_init_num_threads();`
in torch/include/ATen/Parallel.h.

**Comment by rusty1s** [comment]
Okay, do you wanna take care of this?

**Comment by rusty1s** [comment]
We would just need to add this here: https://github.com/rusty1s/pytorch_scatter/blob/master/.github/workflows/testing.yml#L30

**Comment by HunterTracer** [comment]
Can I use python code in testing.yml to replace the context? If so, maybe I can try, since I'm not quite familiar with the bash language.

**Comment by rusty1s** [comment]
I think you can, but using `sed` this should be a one-liner, see [here](https://unix.stackexchange.com/questions/303644/how-can-i-use-sed-or-ex-to-replace-a-block-multi-line-code-with-new-block-of-t):

```
sed -i "" '3,5c\
TORCH_API void lazy_init_num_threads();' Parallel.h
```
where `3` and `5` indicate the start and end line you want to replace.

**Comment by HunterTracer** [comment]
This can work if Parallel.h in all versions of pytorch remains the same. If the source code change the position of lazy_init_num_threads, such method may fail.

**Comment by rusty1s** [comment]
Yes, that is correct. We would need to adjust line numbers both for PyTorch 1.12 and 1.13

**Comment by HunterTracer** [comment]
Fortunately, for pytorch 1.12 and 1.13, the positions are the same, both of them are 32-38

**Comment by HunterTracer** [comment]
I just add the text replacement 

sed -i '32,38c\
TORCH_API void lazy_init_num_threads();' "$(python -c "import os, torch; print(os.path.join(os.path.dirname(torch.__file__), 'include/ATen/Parallel.h'))")"

**Comment by HunterTracer** [comment]
Sorry for that, I made a mistake, for pytorch 1.12, the lines should be 31-37.

**Comment by rusty1s** [comment]
Yeah, I think I have fixed this.

**Comment by HunterTracer** [comment]
OK, thanks!

**Pull request merged**
